/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oJHqY0iwA3z
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Comfortaa } from 'next/font/google'
import { Syne } from 'next/font/google'

comfortaa({
  subsets: ['latin'],
  display: 'swap',
})

syne({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="flex flex-col min-h-dvh">
      <header className="bg-[#ff7b00] text-white px-4 md:px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <CalendarIcon className="h-6 w-6" />
            <span className="text-xl font-bold">Event Planner</span>
          </Link>
          <nav className="hidden md:flex gap-4">
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Upcoming Events
            </Link>
            <Link href="#" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
              Past Events
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4">
          <Link
            href="#"
            className="inline-flex h-9 items-center justify-center rounded-md bg-white px-4 py-2 text-sm font-medium text-[#ff7b00] shadow transition-colors hover:bg-[#ffa04d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Log In
          </Link>
          <Link
            href="#"
            className="inline-flex h-9 items-center justify-center rounded-md bg-[#ffa04d] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ffb733] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Sign Up
          </Link>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container space-y-12 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm text-[#ff7b00]">Upcoming Events</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Discover Exciting Events</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore a wide range of events and find the perfect one for you. From conferences to workshops, we have
                  got it all.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md bg-[#ff7b00] px-8 text-sm font-medium text-white shadow transition-colors hover:bg-[#ffa04d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  View Events
                </Link>
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-[#ff7b00] bg-background px-8 text-sm font-medium text-[#ff7b00] shadow-sm transition-colors hover:bg-[#ffa04d] hover:text-white focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Register Now
                </Link>
              </div>
            </div>
            <div className="mx-auto grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <Card className="bg-white shadow-md rounded-lg overflow-hidden">
                <CardHeader className="bg-[#ff7b00] p-4 flex items-center justify-between">
                  <div className="text-white font-bold text-lg">Tech Conference</div>
                  <div className="bg-white text-[#ff7b00] font-bold px-3 py-1 rounded-full text-sm">June 15-17</div>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-muted-foreground">
                    Join us for the annual tech conference, featuring industry-leading speakers and workshops.
                  </p>
                </CardContent>
                <CardFooter className="bg-muted p-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff7b00] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ffa04d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Register
                  </Link>
                </CardFooter>
              </Card>
              <Card className="bg-white shadow-md rounded-lg overflow-hidden">
                <CardHeader className="bg-[#ff7b00] p-4 flex items-center justify-between">
                  <div className="text-white font-bold text-lg">Design Workshop</div>
                  <div className="bg-white text-[#ff7b00] font-bold px-3 py-1 rounded-full text-sm">July 10-12</div>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-muted-foreground">
                    Improve your design skills with our hands-on workshop led by industry experts.
                  </p>
                </CardContent>
                <CardFooter className="bg-muted p-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff7b00] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ffa04d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Register
                  </Link>
                </CardFooter>
              </Card>
              <Card className="bg-white shadow-md rounded-lg overflow-hidden">
                <CardHeader className="bg-[#ff7b00] p-4 flex items-center justify-between">
                  <div className="text-white font-bold text-lg">Marketing Meetup</div>
                  <div className="bg-white text-[#ff7b00] font-bold px-3 py-1 rounded-full text-sm">August 1-3</div>
                </CardHeader>
                <CardContent className="p-4">
                  <p className="text-muted-foreground">
                    Connect with marketing professionals and learn the latest strategies.
                  </p>
                </CardContent>
                <CardFooter className="bg-muted p-4 flex justify-end">
                  <Link
                    href="#"
                    className="inline-flex h-9 items-center justify-center rounded-md bg-[#ff7b00] px-4 py-2 text-sm font-medium text-white shadow transition-colors hover:bg-[#ffa04d] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Register
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">Join Our Community</h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Stay up-to-date with the latest events and connect with like-minded individuals.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex gap-2">
                <Input type="email" placeholder="Enter your email" className="max-w-lg flex-1" />
                <Button type="submit" className="bg-[#ff7b00] text-white hover:bg-[#ffa04d]">
                  Subscribe
                </Button>
              </form>
              <p className="text-xs text-muted-foreground">
                Sign up to receive updates on upcoming events.{" "}
                <Link href="#" className="underline underline-offset-2" prefetch={false}>
                  Terms &amp; Conditions
                </Link>
              </p>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 Event Planner. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}

function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}
